# ===================================
# APPLICATION
# ===================================
spring.application.name=payment-service

# ===================================
# SERVER
# ===================================
server.port=8083

# ===================================
# ORDER SERVICE
# ===================================
order.service.url=http://localhost:8082

# ===================================
# JWT
# ===================================
application.security.jwt.secret-key=shopping-cart-secret-key-shopping-cart-secret-key

# ===================================
# SWAGGER
# ===================================
springdoc.swagger-ui.path=/swagger-ui.html

# ===================================
# LOGGING
# ===================================
logging.level.org.springframework.web=INFO
logging.level.root=INFO