# ===================================
# APPLICATION
# ===================================
spring.application.name=product-service

# ===================================
# SERVER
# ===================================
server.port=8081

# ===================================
# EXTERNAL API
# ===================================
fake.store.api=https://fakestoreapi.com

# ===================================
# SWAGGER
# ===================================
springdoc.swagger-ui.path=/swagger-ui.html

# ===================================
# LOGGING
# ===================================
logging.level.org.springframework.web=INFO
logging.level.root=INFO